In [1]:
import os

In [5]:
print(os.path.exists('/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08'))

True


In [10]:
a = input('폴더명을 입력하세요')
print(os.listdir(a))
if os.path.exists(a) == True:
    os.makedirs(a+'/temp_3')
else:
    os.makedirs(a+'/temp_1')
    

폴더명을 입력하세요/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08
['temp', 'temp_2', '.DS_Store', '실습용 자료', '파일 생성 예제1']


In [344]:
f = open('/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08/실습용 자료/url.txt','r')
b = f.readlines()

In [345]:
print(b)

['https://blog.naver.com/abc123\n', 'https://blog.tistory.com/aaa123\n', 'https://blog.blog.me/bbb456\n', 'https://blog.tistory.com/abc1234\n', 'https://blog.blog.me/ddd432\n', 'https://blog.naver.com/bbaacc234\n', 'https://blog.naver.com/aacc5435']


In [372]:
b[1].split('/')[2]

'blog.tistory.com'

In [362]:
a = []
for i in range(len(b)):
    a.append(b[i].split('/')[2])

In [369]:
c1 = 0
c2 = 0
c3 = 0
for i in range(len(a)):
    if a[i] == 'blog.naver.com':
        c1 +=1
    elif a[i] == 'blog.blog.com':
        c2 +=1
    elif a[i] == 'blog.tistory.com':
        c3 += 1
        
print(c1,c2,c3)
#이거 다시 

3 0 2


In [378]:
import pandas as pd
import openpyxl
from openpyxl import load_workbook

In [113]:
Comments = openpyxl.load_workbook('/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08/실습용 자료/댓글내용.xlsx')
sheet = Comments['Sheet1']

contents = {  }
for i in range(2, sheet.max_row+1):
    comments = sheet.cell(row = i, column = 2).value
    print(comments)

#이거 진짜 중요함

첫번째 댓글입니다
두번째 댓글입니다
세번째 댓글입니다
네번째 댓글입니다
다섯번째 댓글입니다


In [150]:
f = open('/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08/실습용 자료/예외처리연습1.txt','r', encoding = 'utf-8')
num =f.readlines()

In [188]:
num = int(input('몇번을 입력받을까요?'))

try:
    for i in range(num):
        print(Ex[i])
except:
    if num >= 6:
        print('모든 행이 출력이 완료되었습니다.')
else:
    for i in range(num):
        print(Ex[i])
        
        

몇번을 입력받을까요?7
홍길동

일지매

전우치

강감찬

신사임당 

모든 행이 출력이 완료되었습니다.


In [190]:
import numpy as np

In [240]:
a = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(a)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [241]:
b = a[0][1]
c = a[1][2]
d = []
d.append(b)
d.append(c)
print(d)

[20, 60]


In [243]:
b = a[0][1:3]
c = a[1][1:3]
f = np.array([b,c])
print(f)

[[20 30]
 [50 60]]


In [244]:
import pandas as pd

In [258]:
M = {'번호' : ['1번', '2번', '3번'],
     '이름' : ['홍길동','전우치','강감찬']}
M1 = pd.DataFrame(M)
M2 = pd.Series(['1975', '', '1982'])

M3 = pd.DataFrame()
M3['번호'] = M1['번호']
M3['이름'] = M1['이름']
M3['생일'] = M2
M3

번호   이름    생일
0  1번  홍길동  1975
1  2번  전우치      
2  3번  강감찬  1982

In [572]:
df = pd.read_excel('/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08/실습용 자료/부품구입대장.xlsx')
df1 = df.drop(df.index[0:3])
df1
df1.columns = ['날짜', '사업장', '품목', '수량', '단가', '금액']

In [573]:
df1 = df1.reset_index()

In [574]:
df2 =df1[['날짜','품목','수량','금액']]
df2

날짜          품목  수량        금액
0   2019-08-23 00:00:00       ANGLE  21    672000
1   2019-09-09 00:00:00          백관  44   2464000
2   2019-06-18 00:00:00         절연판  40   1800000
3   2019-03-13 00:00:00  P/Z O-RING  11    418000
4   2019-05-11 00:00:00         알코올  38    304000
5   2019-06-28 00:00:00         실리콘  30   4500000
6   2019-02-16 00:00:00         소모품   4      8800
7   2019-10-22 00:00:00       MOTOR  14    420000
8   2019-03-18 00:00:00  PAPER BRSH  13    520000
9   2019-07-17 00:00:00        불화카리  23   1909000
10  2019-07-23 00:00:00         마크펜  33     99000
11  2019-03-20 00:00:00         NUT  20    300000
12  2019-01-27 00:00:00         윤활유  30  60000000
13  2019-07-11 00:00:00         소모품  50    110000
14  2019-05-16 00:00:00        BITE  14   1204000

In [575]:
df2.loc[df2['금액'] > 1000000].sort_values(['금액'], ascending = [False])
#금액을 기준으로 내림차순 

날짜    품목  수량        금액
12  2019-01-27 00:00:00   윤활유  30  60000000
5   2019-06-28 00:00:00   실리콘  30   4500000
1   2019-09-09 00:00:00    백관  44   2464000
9   2019-07-17 00:00:00  불화카리  23   1909000
2   2019-06-18 00:00:00   절연판  40   1800000
14  2019-05-16 00:00:00  BITE  14   1204000

In [576]:
df3 = df2.loc[df2['금액'] > 1000000].sort_values(['금액'], ascending = [False])
df3[['품목', '금액']]
#품목과 금액만 출력 

품목        금액
12   윤활유  60000000
5    실리콘   4500000
1     백관   2464000
9   불화카리   1909000
2    절연판   1800000
14  BITE   1204000

In [579]:
df2['코드'] = ' '

/Users/Moon/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [589]:
for i in range(len(df2['품목'])):
    if df2.iloc[:,1][i] == '백관':
        df2.iloc[:,4][i] = 'A1'
    elif df2.iloc[:,1][i] == '절연판':
        df2.iloc[:,4][i] = 'B1'
    elif df2.iloc[:,1][i] == '실리콘':
        df2.iloc[:,4][i] = 'C1'
    else:
        df2.iloc[:,4][i] = ' '

In [590]:
df2

날짜          품목  수량        금액  코드
0   2019-08-23 00:00:00       ANGLE  21    672000    
1   2019-09-09 00:00:00          백관  44   2464000  A1
2   2019-06-18 00:00:00         절연판  40   1800000  B1
3   2019-03-13 00:00:00  P/Z O-RING  11    418000    
4   2019-05-11 00:00:00         알코올  38    304000    
5   2019-06-28 00:00:00         실리콘  30   4500000  C1
6   2019-02-16 00:00:00         소모품   4      8800    
7   2019-10-22 00:00:00       MOTOR  14    420000    
8   2019-03-18 00:00:00  PAPER BRSH  13    520000    
9   2019-07-17 00:00:00        불화카리  23   1909000    
10  2019-07-23 00:00:00         마크펜  33     99000    
11  2019-03-20 00:00:00         NUT  20    300000    
12  2019-01-27 00:00:00         윤활유  30  60000000    
13  2019-07-11 00:00:00         소모품  50    110000    
14  2019-05-16 00:00:00        BITE  14   1204000

In [442]:
Data = pd.read_excel('/Users/Moon/Desktop/빅데이터 청년인재/Python/2020-07-08/실습용 자료/학생_만족도_조사_실습.xlsx')
Data


연번   학년  소속  분반 1. 튜터링 활동을 위한 자료준비 및 선행학습은 적절하였다.  \
0   1.0  4.0   7 NaN                                 5   
1   2.0  4.0   4 NaN                                 3   
2   3.0  4.0   5 NaN                                 3   
3   4.0  3.0   1 NaN                                 5   
4   5.0  3.0  12 NaN                                 4   
..  ...  ...  ..  ..                               ...   
73  NaN  NaN  11 NaN                                 0   
74  NaN  NaN  12 NaN                                 0   
75  NaN  NaN  13 NaN                                 0   
76  NaN  NaN  14 NaN                                 0   
77  NaN  NaN  15 NaN                                 0   

   2. 튜티의 학습 수준 및 특성을 파악하였다. 3. 활동 중 튜티와의 상호작용을 유도하였다.  \
0                          5                         5   
1                          4                         4   
2                          4                         4   
3                          5                         5   
4                          4                         5   
..                       ...                       ...   
73                         0                         3   
74                         0                         9   
75                         0                         3   
76                         0                         3   
77                         3                         7   

   4. 튜티의 학습 수준 및 특성을 고려하여 활동하였다. 5. 튜터링 활동 시간은 적절하였다.  6. 튜터링 활동 장소는 적절하였다.  \
0                               5                    5                   5.0   
1                               4                    4                   4.0   
2                               5                    4                   4.0   
3                               5                    5                   5.0   
4                               4                    3                   4.0   
..                            ...                  ...                   ...   
73                             21                   34                   NaN   
74                             24                   25                   NaN   
75                             21                   34                   NaN   
76                             25                   30                   NaN   
77                             24                   24                   NaN   

    ...  11. 책임감이 증진되었다.  12. 협동심이 증진되었다.  13. 의사소통능력이 증진되었다.  \
0   ...         5.000000         5.000000            5.000000   
1   ...         4.000000         4.000000            4.000000   
2   ...         4.000000         3.000000            4.000000   
3   ...         5.000000         5.000000            5.000000   
4   ...         4.000000         3.000000            4.000000   
..  ...              ...              ...                 ...   
73  ...         0.051724         0.362069            0.586207   
74  ...         0.155172         0.413793            0.431034   
75  ...         0.051724         0.362069            0.586207   
76  ...         0.051724         0.431034            0.517241   
77  ...         0.120690         0.413793            0.413793   

    14. 티칭스킬이 증진되었다.  15. 학교생활 적응능력이 증진되었다.  16. 효원튜터링 프로그램에 대해 만족한다.  \
0                5.0                    5.0                        만족   
1                4.0                    4.0                        만족   
2                5.0                    4.0                        만족   
3                5.0                    5.0                        만족   
4                5.0                    5.0                        만족   
..               ...                    ...                       ...   
73               NaN                    NaN                       NaN   
74               NaN                    NaN                       NaN   
75               NaN                    NaN                       NaN   
76               NaN                    NaN                       NaN   
77               NaN                    NaN                       

In [443]:
Data2 = Data[['팀활동좋았던점','운영상 좋았던점']]
Data2

팀활동좋았던점                                   운영상 좋았던점
0       의사소통 능력, 리더쉽 능력이 승진되었다.                   보고서를 통해 피드백을 받을 수 있어 좋았다
1   다른과에서 복수전공을 하고오신 튜티를 만나 좋았다  주간 보고서를 제풀해야해서 주당 1회 활동이 의무적으로 이루어 진 것 같다
2                     무난하게 잘 완료                    전공 과목을 대상으로 한다는 점에서 도움됨
3                      질의응답이 활발                              설명을 잘해주셔서 좋았다
4                           NaN                         자율적인 튜터링 활동이어서 좋았다
..                          ...                                        ...
73                          NaN                                        NaN
74                          NaN                                        NaN
75                          NaN                                        NaN
76                          NaN                                        NaN
77                          NaN                                        NaN

[78 rows x 2 columns]